sonar.projectKey=bankease-reactnative-merchant
sonar.projectName=BankEase Merchant Dashboard
sonar.projectVersion=1.0.0

# Sources
sonar.sources=.
sonar.inclusions=**/*.ts,**/*.tsx,**/*.js,**/*.jsx

sonar.exclusions=\
  **/node_modules/**,\
  **/android/**,\
  **/ios/**,\
  **/.expo/**,\
  **/coverage/**,\
  **/dist/**,\
  **/*.test.ts,\
  **/*.test.tsx,\
  **/e2e/**,\
  **/modules/**,\
  **/mocks/**,\
  **/.git/**

# Skip npm audit / dependency scanning (speeds up scan)
sonar.dependencyCheck.skip=true
# Disable SCM to speed up
sonar.scm.disabled=true

# Test files
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.tests=.

# TypeScript
sonar.typescript.tsconfigPath=tsconfig.json

# Encoding
sonar.sourceEncoding=UTF-8

# Coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info
